version: '3'
services:
  devpi:
    # docker-compose settings
    build: .
    container_name: devpi
    # docker swarm settings
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    # general settings
    image: devpi
    ports:
      - "8001:80/tcp"
    volumes:
      - ./devpi:/data/devpi
      - ./nginx:/data/nginx:ro
